// TodoMvc/todos-vue2/src/components/TodoMain.vue
<template>
  <ul class="todo-list">
    <li :class="{completed: obj.isDone}" v-for="obj in arr" :key="obj.id">
      <div class="view">
        <input class="toggle" type="checkbox" v-model="obj.isDone">
        <label>{{ obj.name }}</label>
        <button class="destroy" @click="del(obj.id)"></button>
      </div>
    </li>
  </ul>
</template>

<script>
export default {
  name: "TodoMain",
  // 通过 props 接收父组件App传过来的 任务列表数组
  props: ["arr"],
  methods: {
    del(id) {
      this.$emit("delFn", id)
    }
  }
}
</script>

<style scoped>

</style>

// TodoMvc/todos-React/vite-project-react/src/components/ToDoMain.jsx
const ToDoMain = () => {

  return (
    <ul className="todo-list">

      <li className={1 ? 'completed' : ''}>
        <div className="view">
          <input className="toggle" type="checkbox" onChange={} />
          <label>name</label>
          <button className="destroy"></button>
        </div>
      </li>

    </ul>
  )
}

export default ToDoMain
