// TodoMvc/todos-vue2/src/components/TodoFooter.vue
<template>
  <footer class="footer">
    <span class="todo-count">剩余 <strong>{{ count }}</strong></span>
    <ul class="filters">
      <li>
        <a :class="{ selected: isSel === 'all'}" href="javascript:;" @click="changeType('all')">全部</a>
      </li>
      <li>
        <a :class="{selected: isSel === 'no'}" href="javascript:;" @click="changeType('no')">未完成</a>
      </li>
      <li>
        <a :class="{selected: isSel === 'yes'}" href="javascript:;" @click="changeType('yes')">已完成</a>
      </li>
    </ul>
    <button class="clear-completed" @click="clearFn">清除已完成</button>
  </footer>
</template>

<script>
export default {
  name: "TodoFooter",
  props: ['fooArr'],
  data() {
    return {
      isSel: 'all'
    }
  },
  methods: {
    // 改变选择类型
    changeType(src) {
      this.isSel = src;
      this.$emit('changeFn', src)
    },
    clearFn() {
      this.$emit('clear')
    }
  },
  computed: {
    count() {
      return this.fooArr.length
    }
  }
}
</script>

<style scoped>

</style>

// TodoMvc/todos-React/vite-project-react/src/components/ToDoFooter.jsx
const ToDoFooter = ({num, clearTask, changeType}) => {

  return (
    <footer className="footer">
      <span className="todo-count">剩余<strong>0</strong></span>
      <ul className="filters">
        <li>
          <a onClick={() => changeType('all')} href="#/">全部</a>
        </li>
        <li>
          <a onClick={() => changeType('no')} href="#/active">未完成</a>
        </li>
        <li>
          <a onClick={() => changeType('yes')} href="#/completed">已完成
          </a>
        </li>
      </ul>
      <button className="clear-completed"> 清除已完成< /button>
    </footer>
  )
}
export default ToDoFooter
