// TodoMvc/todos-React/vite-project-react/src/components/ToDoMain.jsx
const ToDoMain = () => {

  return (
    <ul className="todo-list">

      <li className={1 ? 'completed' : ''}>
        <div className="view">
          <input className="toggle" type="checkbox" onChange={} />
          <label>name</label>
          <button className="destroy"></button>
        </div>
      </li>

    </ul>
  )
}

export default ToDoMain

// TodoMvc/todos-vue3/src/components/TodoMain.vue
<template>
  <ul class="todo-list">
    <!-- completed: 完成的类名 -->
    <li
        :class="{completed: item.flag}"
        v-for="item in props.taskList"
        :key="item.id"
    >
      <div class="view">
        <input class="toggle" type="checkbox" v-model="item.flag" />
        <label>{{ item.name }}</label>
        <button @click="delTask(item.id)" class="destroy"></button>
      </div>
    </li>
  </ul>
</template>

<script setup>
const props = defineProps({
  taskList: Array
})
const emit = defineEmits(['delTaskFn'])

const delTask = (id) => {
  emit('delTaskFn', id)
}
</script>

<style scoped>
</style>
