// TodoMvc/todos-React/vite-project-react/src/components/TodoHeader.jsx
const TodoHeader = ({add, checkedAllFn, changeCheckAll}) => {

  return (
    <header className="header">
      <h1 >todos</h1>
      <input
        id="toggle-all"
        className="toggle-all"
        type="checkbox"
      />
      <label htmlFor="toggle-all"></label>
      <input
        className="new-todo"
        placeholder="输入任务名称-回车确认"
        autoFocus
      />
    </header>
  )
}

export default TodoHeader

// TodoMvc/todos-vue3/src/components/TodoHeader.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input
        id="toggle-all"
        class="toggle-all"
        type="checkbox"
        v-model="isAll"
    >
    <label for="toggle-all"></label>
    <input
        class="new-todo"
        placeholder="输入任务名称-回车确认"
        autofocus
        v-model="taskName"
        @keydown.enter="addTask"
    />
  </header>
</template>

<script setup>
import {computed, ref} from "vue";

const emit = defineEmits(['addTaskFn'])

const taskName = ref('')
const addTask = () => {
  if (taskName.value.trim().length === 0) return alert('不能为空')
  emit('addTaskFn', taskName.value)
  taskName.value = ''
}

const props = defineProps(['arr'])
// 全选反选
const isAll = computed({
  get() {
    return props.arr.every(item => item.flag)
  },
  set(checked) {
    props.arr.forEach(item => item.flag = checked)
  }
})
</script>

<style scoped>

</style>
